from .downloadOrtoFotoTask import DownloadOrtofotoTask
from .downloadNmtTask import DownloadNmtTask
from .downloadLasTask import DownloadLasTask
from .downloadReflectanceTask import DownloadReflectanceTask