from .downloadOrtoFotoTask import DownloadOrtofotoTask
from .downloadNmtTask import DownloadNmtTask
from .downloadLasTask import DownloadLasTask
from .downloadReflectanceTask import DownloadReflectanceTask
from .downloadBdotTask import DownloadBdotTask
from .downloadBdooTask import DownloadBdooTask